---
title: "Quantitative genetics of health-related traits in a small-scale society"
author: Jannik Briand
affiliation: University of Zurich
# date: "05/07/2022"
output: pdf_document
fontfamily: libertine
fontsize: 11pt
---

___


Understanding the genetic and environmental bases of complex physical and behavioral traits is crucial for developing effective interventions to promote health-related outcomes. Quantitative genetic models are widely used to address this challenge and estimate the heritable basis of complex human phenotypes. However, recent work shows that a failure to account for how local environments shape genetic expression, i.e. gene-by-environment interaction or phenotypic plasticity, has lead previous studies to systematically overestimate the genetic bases of human traits. In this project, we will apply novel models that directly estimate environmental effects on gene expression to re-evaluate the heritability of health traits, drawing on long-term field data collected in a small-scale human society.

___


# Introduction

Test test

# Review of the Literature

Test test

# Methods

Test test

# Results

Test test

# Discussion

Test test
